name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@e2a42bc9a15f8414a9078f38b702de2a2976733d # v3
        with:
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: true
      - name: Build the Docker image
        shell: bash
        run: |
          ./build.sh --testing